import {jsPDF} from "jspdf";
import {taylorLogoJpeg} from "../../taylor-logo";
import {normalizeProductTerminology} from "../../panel-config";
type Q=Record<string,any>;const c=(v:any)=>String(v??"").replace(/[•·]/g," | ").replace(/[–—]/g,"-");
function createPdf(q:Q){try{const d=new jsPDF({unit:"pt",format:"letter"}),L=28,W=556;let y=102;
 const logo=()=>d.addImage(`data:image/jpeg;base64,${taylorLogoJpeg}`,"JPEG",L,20,122,48);
 const frame=()=>{logo();d.setFillColor(197,210,227);d.setDrawColor(148,165,184);d.rect(335,20,249,66,"FD");d.setTextColor(21,47,72);d.setFont("helvetica","bold");d.setFontSize(15);d.text("ORDER SUMMARY",347,39);d.setFont("helvetica","normal");d.setFontSize(8);d.text(`Order #: ${c(q.orderNumber)}`,347,54);d.text(`PO #: ${c(q.poNumber)||"Not provided"}`,347,67);d.text(`Date: ${c(q.submitted)}`,462,54);d.text(`Requested: ${c(q.project?.requestedDate)||"Not set"}`,462,67)};
 const next=()=>{d.addPage();frame();y=102},ensure=(h:number)=>{if(y+h>742)next()};
 const band=(s:string)=>{ensure(24);d.setFillColor(174,194,219);d.setDrawColor(93,118,146);d.rect(L,y,W,20,"FD");d.setTextColor(18,48,76);d.setFont("helvetica","bold");d.setFontSize(9);d.text(s,L+7,y+14);y+=20};
 const info=(x:number,title:string,rows:string[])=>{d.setFillColor(197,210,227);d.rect(x,y,271,19,"F");d.setTextColor(21,47,72);d.setFont("helvetica","bold");d.setFontSize(8);d.text(title,x+6,y+13);d.setFont("helvetica","normal");d.setTextColor(30,43,55);let ry=y+32;rows.forEach(r=>{const w=d.splitTextToSize(c(r),259);d.text(w,x+6,ry);ry+=Math.max(11,w.length*9)});d.setDrawColor(180,190,200);d.rect(x,y,271,Math.max(94,ry-y));return Math.max(94,ry-y)};
 const table=(hs:string[],ws:number[],rows:string[][])=>{const head=()=>{let x=L;hs.forEach((h,i)=>{d.setFillColor(207,218,232);d.setDrawColor(110,130,150);d.rect(x,y,ws[i],20,"FD");d.setTextColor(24,51,76);d.setFont("helvetica","bold");d.setFontSize(7.2);d.text(h,x+4,y+13);x+=ws[i]});y+=20};head();rows.forEach(r=>{const wrap=r.map((v,i)=>d.splitTextToSize(c(v),ws[i]-8)),h=Math.max(21,...wrap.map(v=>v.length*9+7));if(y+h>742){next();head()}let x=L;wrap.forEach((v,i)=>{d.setFillColor(255,255,255);d.setDrawColor(177,188,199);d.rect(x,y,ws[i],h,"FD");d.setTextColor(25,38,50);d.setFont("helvetica","normal");d.setFontSize(7.5);d.text(v,x+4,y+12);x+=ws[i]});y+=h})};
 frame();const a=info(L,"PURCHASING COMPANY",[q.company?.name,`Account: ${q.company?.account||"Not provided"}`,`Contact: ${q.company?.contact||"Not provided"}`,q.company?.email,q.company?.address,`Payment: ${q.company?.payment}`]),b=info(L+285,"PROJECT INFORMATION",[`Job: ${q.project?.jobName}`,`Project: ${q.project?.projectName||"Not provided"}`,`Receiving: ${q.project?.receivingContact}`,`Delivery: ${q.project?.delivery}`,`Submitted by: ${q.submittedBy}`]);y+=Math.max(a,b)+12;
 band("PANELS");const pr:string[][]=[];(q.panels||[]).forEach((p:any,i:number)=>{pr.push([p.totalPanels,`${i+1}. ${p.name} - ${p.coverage}`,p.gauge,normalizeProductTerminology(p.finish),p.color,[p.pan,p.notching,p.roofPitch?`Pitch ${p.roofPitch}`:"",p.clip,p.coil?`Coil ${p.coil}`:""].filter(Boolean).join(" | ")]);(p.lengths||[]).forEach((r:any)=>pr.push([r.qty,`Length: ${r.feet} ft ${r.inches} in`,"","","",""]))});table(["QTY","ITEM DESCRIPTION","GA./MATERIAL","FINISH","COLOR","OPTIONS"],[38,170,72,72,100,104],pr.length?pr:[["0","No panels configured","","","",""]]);d.setFillColor(237,242,247);d.rect(L,y,W,22,"F");d.setTextColor(35,55,73);d.setFont("helvetica","bold");d.setFontSize(8);d.text(`PANEL TOTAL: ${q.totals?.panels||0}`,L+7,y+15);d.text(`COVERAGE AREA: ${(q.totals?.area||0).toLocaleString()} SQ FT`,L+180,y+15);y+=30;
 band("ACCESSORIES");table(["QTY","UNIT","TYPE","ITEM DESCRIPTION","PART"],[45,65,100,260,86],q.accessories?.length?q.accessories.map((x:any)=>[x.quantity,x.unit,x.category,x.name,x.part]):[["0","","","No accessories selected",""]]);y+=10;band("FLASHINGS");table(["QTY","ITEM DESCRIPTION","GA./MATERIAL","COLOR"],[45,286,105,120],q.flashings?.length?q.flashings.map((x:any)=>[x.quantity,x.name,q.flashingFinish.gauge,q.flashingFinish.color]):[["0","No flashings selected",q.flashingFinish?.gauge,q.flashingFinish?.color]]);y+=10;if(q.project?.notes){band("PROJECT NOTES");const n=d.splitTextToSize(c(q.project.notes),W-14);d.setTextColor(30,43,55);d.setFont("helvetica","normal");d.setFontSize(8);d.text(n,L+7,y+13)}
 const pages=d.getNumberOfPages();for(let p=1;p<=pages;p++){d.setPage(p);frame();d.setDrawColor(155,171,188);d.line(L,757,L+W,757);d.setTextColor(53,73,92);d.setFont("helvetica","bold");d.setFontSize(7);d.text("RIVERSIDE CA | SACRAMENTO CA | SALEM OR | AUBURN WA | SPOKANE WA | TAYLORMETAL.COM",L,772);d.text(`Page ${p} of ${pages}`,584,772,{align:"right"})}const name=c(q.filename||"taylor-metal-order.pdf").replace(/[^a-zA-Z0-9._-]/g,"-");return new Response(d.output("arraybuffer"),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="${name}"`,"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}catch(e){console.error(e);return new Response("Unable to generate order PDF",{status:400})}}

export async function POST(request:Request){try{return createPdf(await request.json() as Q)}catch(e){console.error(e);return new Response("Unable to generate order PDF",{status:400})}}
export async function GET(request:Request){try{return createPdf(JSON.parse(new URL(request.url).searchParams.get("payload")||"") as Q)}catch(e){console.error(e);return new Response("Unable to generate order PDF",{status:400})}}
